### ISSUE TITLE
Why did you change dirty_write to transaction in tables.erl?

### ISSUE THREAD

**Issue by bailud** [sitstone/erl#1]
I saw you have commented out mnesia:dirty_write in line 21 of src/tables.erl, and changed it to mnesia:transaction in line 26. Could you explain what is wrong with the mnesia:dirty_write and why you changed it?

**Comment by linchengcs** [comment]
Hi, bailud, surpriesed somebody will really check out this code. This is a miscellaneous repo when I first study erlang and put everything in, so it is highly possible the code is hard to use and read. Now my erlang blog in production only use mysql db because I don't have much time to maintain mnesia/mongo etc, and I have removed anything irrelevant to blog.
About the question, I guess there may be two reasons (not sure which is the real one): 1) line 21 doesn't work  2) line 21 works but I was trying the transaction feature.

**Comment by bailud** [comment]
@sitstone Did you use MySQL db alone or with the ODBC in Erlang?

**Comment by linchengcs** [comment]
@bailud I use [emysql](https://github.com/Eonblast/Emysql)

**Comment by linchengcs** [comment]
closing
